language: python

services:
  - docker

python:
  - 3.7

before_install:
  - docker build -t churn -f docker/Dockerfile .
  - docker ps -a
  - python --version

install:
  - pip install -U pip
  - pipenv install
  - pip install codecov

script: cd src/python; pytest tests/

after_success:
  - codecov
