language: python

services:
  - docker

python:
  - 3.7

before_install:
  - docker-compose -f docker/docker-compose.yml build
  - docker ps -a
  - python --version

install:
  - pip install -U pip
  - pipenv install

script: cd src/python; pytest tests/
