artifact_uri: tracking/0/2ec2c06738e7466bbdd7d8dd31d3d390/artifacts
end_time: 1608434234076
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 2ec2c06738e7466bbdd7d8dd31d3d390
run_uuid: 2ec2c06738e7466bbdd7d8dd31d3d390
source_name: ''
source_type: 4
source_version: ''
start_time: 1608434234001
status: 3
tags: []
user_id: root
